[package]
name = "dagster_pipes_rust"
version = "0.1.7"
edition = "2021"
description = "A Dagster pipes implementation for interfacing with Rust"
license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0"
flate2 = "1"
thiserror = "2.0.3"
clap = { version = "4.5.23", features = ["derive"], optional = true}

[dev-dependencies]
rstest = { version = "0.23.0", default-features = false }
tempfile = "3.14.0"

[workspace]
members = ["example-dagster-pipes-rust-project/rust_processing_jobs"]

[features]
pipes-tests = ["dep:clap"]

[[bin]]
name = "pipes_tests"
required-features = ["pipes-tests"]
