[general]
error_reporting = false

[messages]
log = true
report_custom_message = true
report_asset_materialization = true
report_asset_check = false
log_external_stream = false

[message_channel]
s3 = false
databricks = false
