[project]
name = "dagster-hex"
version = "0.1.2"
description = "Dagster integration with Hex"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dagster>=1.3",
    "dagit",
    "requests>=2",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "types-requests",
    "pytest-mock",
    "requests-mock",
]

[tool.setuptools]
packages = ["dagster_hex"]
