[project]
name = "dagster-hex"
version = "0.1.2"
description = "Dagster integration with Modal"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dagster>=1.3",
    "dagit",
    "requests>=2",
]

[tool.uv]
dev-dependencies = [
    "mypy>=0.8",
    "pytest",
    "pre-commit",
    "flake8",
    "isort",
    "types-requests",
    "black",
    "pytest-mock",
    "requests-mock",
]
