[project]
name = "dagster-hightouch"
version = "0.1.5"
author = "Pedram Navid"
author_email = "pedram@hightouch.io"
description = "Dagster library for Hightouch"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dagster>=0.14",
    "requests>=2.0",
]
