[project]
name = "dagster-hightouch"
version = "0.1.5"
description = "Dagster library for Hightouch"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dagster>=0.14",
    "requests>=2.0",
]
