name: dagster-pipes-tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - "libraries/pipes/tests/dagster-pipes-tests/**"
      - ".github/workflows/libraries-pipes-tests.yml"

defaults:
  run:
    working-directory: ./libraries/pipes/tests/dagster-pipes-tests

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4

      - name: "Run Tests"
        run: uv run pytest
