name: dagster-pipes-java

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - "libraries/pipes/tests/dagster-pipes-tests/**"
      - "libraries/pipes/implementations/java/**"
      - ".github/workflows/libraries-pipes-java.yml"

defaults:
  run:
    working-directory: ./libraries/pipes/implementations/java/dagster-pipes-java/

jobs:
  integration-tests:
    name: "Dagster Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run tests
        run: |
          nix develop --command \
            bash -c "uv run pytest"
