name: quality-check-dagster-teradata
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/dagster-teradata/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './libraries/dagster-teradata'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ${{ inputs.working_directory }}
        run: uv python install 3.12

      - name: Sync dependencies
        working-directory: ${{ inputs.working_directory }}
        run: uv sync

      - name: Ruff
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff check

      - name: Pyright
        working-directory: ${{ inputs.working_directory }}
        run: uv run pyright

      - name: Pytest
        working-directory: ${{ inputs.working_directory }}
        run: uv run pytest --ignore=dagster_teradata_tests/functional/
