name: quality-check-dagster-obstore
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/dagster-obstore/**'

jobs:
  check:
    uses: ./.github/workflows/quality-check-dagster-obstore-template.yml
    with:
      working_directory: ./libraries/dagster-obstore
