name: quality-check-dagster-obstore

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "${{ inputs.working_directory }}/docker-compose.yml"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync

      - name: Ruff
        run: uv run ruff check

      - name: Pyright
        run: uv run pyright

      - name: Pytest
        run: uv run pytest
