name: quality-check-dagster-iceberg
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/dagster-iceberg/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ./libraries/dagster-iceberg
        run: uv python install 3.12

      - name: Sync dependencies
        working-directory: ./libraries/dagster-iceberg
        run: uv sync --all-extras --group docs

      - name: Ruff check
        working-directory: ./libraries/dagster-iceberg
        run: uv run ruff check

      - name: Ruff format
        working-directory: ./libraries/dagster-iceberg
        run: uv run ruff format --check

      - name: Pyright
        working-directory: ./libraries/dagster-iceberg
        run: uv run pyright

      - name: Pytest
        working-directory: ./libraries/dagster-iceberg
        run: uv run pytest
