# Build and deployment for `dagster-hex`

on:
  push:
    tags:
      - 'dagster-hex-v*.*.*'

defaults:
  run:
    working-directory: ./libraries/dagster-hex

jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
          UV_PUBLISH_URL: ${{ vars.UV_PUBLISH_URL }}
