# Build and deployment for `dagster-modal`
#
# References
#
#     https://docs.astral.sh/uv/guides/integration/github/
#     https://docs.astral.sh/uv/guides/publish/#preparing-your-project-for-packaging
#

on:
  push:
    tags:
      - 'dagster-modal-v*.*.*'

defaults:
  run:
    working-directory: ./libraries/dagster-modal

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish  # references UV_PUBLISH_TOKEN, UV_PUBLISH_USERNAME, UV_PUBLISH_PASSWORD
