name: build-and-release-dagster-teradata

on:
  push:
    tags:
      - 'dagster_teradata-*.*.*'

jobs:
  build-and-release-dagster-teradata:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-teradata
      working_directory: ./libraries/dagster-teradata
    secrets: inherit
