# Build and deployment for `dagster-hex`

on:
  push:
    tags:
      - 'dagster-hex-v*.*.*'

jobs:
  build-and-deploy:
    uses: .github/workflows/template-release.yml
    with:
      library_name: dagster-hex
      working_directory: ./libraries/dagster-hex
    secrets: inherit
