# Build and deployment for `dagster-modal`
#
# References
#
#     https://docs.astral.sh/uv/guides/integration/github/

on:
  push:
    tags:
      - 'dagster-modal-v*.*.*'

defaults:
  run:
    working-directory: ./libraries/dagster-modal

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Set up Python
        run: uv build
