name: Build and release dagster-hex

on:
  push:
    tags:
      - 'dagster-hex-v*.*.*'

jobs:
  build-and-release-dagster-hex:
    uses: .github/workflows/template-release.yml
    with:
      library_name: dagster-hex
      working_directory: ./libraries/dagster-hex
    secrets: inherit
