name: build-and-release-dagster-modal

on:
  push:
    tags:
      - 'dagster_modal-*.*.*'

jobs:
  build-and-release-dagster-modal:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-modal
      working_directory: ./libraries/dagster-modal
    secrets: inherit
