name: build-and-release-dagster-sdf

on:
  push:
    tags:
      - 'dagster_sdf-*.*.*'

jobs:
  build-and-release-dagster-sdf:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-sdf
      working_directory: ./libraries/dagster-sdf
    secrets: inherit
