name: build-and-release-dagster-anthropic

on:
  push:
    tags:
      - 'dagster_anthropic-*.*.*'

jobs:
  build-and-release-dagster-anthropic:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-anthropic
      working_directory: ./libraries/dagster-anthropic
    secrets: inherit
