name: build-and-release-dagster-contrib-modal

on:
  push:
    tags:
      - 'dagster_contrib_modal-*.*.*'

jobs:
  build-and-release-dagster-contrib-modal:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-contrib-modal
      working_directory: ./libraries/dagster-contrib-modal
    secrets: inherit
