name: quality-check

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ${{ inputs.working_directory }}
        run: uv python install 3.12

      - name: Sync dependencies
        working-directory: ${{ inputs.working_directory }}
        run: uv sync

      - name: Lint
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff check

      - name: Format
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff format --check

      - name: Type check
        working-directory: ${{ inputs.working_directory }}
        run: uv run pyright

      - name: Test
        working-directory: ${{ inputs.working_directory }}
        run: uv run pytest
