name: test-dagster-modal

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/dagster-modal/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install
        working-directory: 'libraries/dagster-modal'

      - name: Sync dependencies
        run: uv sync
        working-directory: 'libraries/dagster-modal'

      - name: Ruff check
        working-directory: 'libraries/dagster-modal'
        run: uv run ruff check

      - name: Run pytest
        working-directory: 'libraries/dagster-modal'
        run: uv run pytest
